### ISSUE TITLE
does not work with deno stdlib

### ISSUE THREAD

**Issue by christophsturm** [stefanicjuraj/docs2llms#1]
I tried it out on the deno std lib just to try it out, but I got a pretty cryptic error message:
```
 % docs2llms --github denoland/std
🚫 Error: No such file or directory (os error 2): stat '/var/folders/m7/q4w431vd3851wjd1x4tmrlvw0000gn/T/a491587b9ca13959/fs/testdata/copy_dir_link_file/0.txt'
```

**Comment by stefanicjuraj** [comment]
Hi @christophsturm, thanks for reporting this issue! I have now fixed it with the release of the version 0.0.6.

<img width="273" alt="screenshot" src="https://github.com/user-attachments/assets/fae95580-8c6d-4d9c-9515-ab94d5359b5a" />
